// AUTO-GENERATED by build-gui.mjs — do not edit manually
export const ROUTING_CONFIG = {
  "out": {
    "master": [
      1
    ],
    "fx1Send": 2,
    "fx2Send": 3,
    "vuSub": 9,
    "vuKick": 8,
    "vuMid": 7,
    "vuTop": 6
  },
  "in": {
    "fx1Return": {
      "channel": 6,
      "mic": false,
      "hpf": 0
    },
    "fx2Return": {
      "channel": 7,
      "mic": false,
      "hpf": 0
    },
    "aux1": {
      "channel": 0,
      "mic": false,
      "hpf": 0
    },
    "aux2": {
      "channel": 1,
      "mic": false,
      "hpf": 0
    },
    "aux3": {
      "channel": 3,
      "mic": false,
      "hpf": 0
    },
    "aux4": {
      "channel": 5,
      "mic": false,
      "hpf": 0
    }
  }
};
