// AUTO-GENERATED by build-gui.mjs — do not edit manually
export const ROUTING_CONFIG = {
  "out": {
    "master": {
      "channels": [
        1
      ],
      "gain": -3
    },
    "fx1Send": {
      "channel": 2,
      "gain": 0
    },
    "fx2Send": {
      "channel": 3,
      "gain": 0
    },
    "vuSub": {
      "channel": 9,
      "gain": 0
    },
    "vuKick": {
      "channel": 8,
      "gain": 0
    },
    "vuMid": {
      "channel": 7,
      "gain": 0
    },
    "vuTop": {
      "channel": 6,
      "gain": 0
    }
  },
  "in": {
    "fx1Return": {
      "channel": 6,
      "mic": false,
      "hpf": 0,
      "gain": 0
    },
    "fx2Return": {
      "channel": 7,
      "mic": false,
      "hpf": 0,
      "gain": 0
    },
    "aux1": {
      "channel": 0,
      "mic": false,
      "hpf": 0,
      "gain": 0
    },
    "aux2": {
      "channel": 1,
      "mic": false,
      "hpf": 0,
      "gain": 0
    },
    "aux3": {
      "channel": 3,
      "mic": false,
      "hpf": 0,
      "gain": 0
    },
    "aux4": {
      "channel": 5,
      "mic": false,
      "hpf": 0,
      "gain": 0
    }
  }
};
