// AUTO-GENERATED by build-gui.mjs — do not edit manually
export const ROUTING_CONFIG = {
  "out": {
    "master": [
      1
    ],
    "fx1Send": 2,
    "fx2Send": 3,
    "vuSub": 9,
    "vuKick": 8,
    "vuMid": 7,
    "vuTop": 6
  },
  "in": {
    "fx1Return": 6,
    "fx2Return": 7,
    "aux1": 0,
    "aux2": 1,
    "aux3": 3,
    "aux4": 5
  }
};
